from django.contrib import admin

from .models import *

admin.site.register(User)

admin.site.register(ModuleButton)
admin.site.register(Overview)
admin.site.register(Sleep)
admin.site.register(WeightExercise)
admin.site.register(CardioExercise)
admin.site.register(Food)
admin.site.register(Toilet)
admin.site.register(Sex)
admin.site.register(Period)
admin.site.register(Money)
admin.site.register(ToDo)
admin.site.register(Pursuit)
admin.site.register(Project)
admin.site.register(Learning)
admin.site.register(Study)
admin.site.register(Literature)
admin.site.register(Film)
admin.site.register(Television)
admin.site.register(VideoGame)
admin.site.register(Music)
admin.site.register(BoardGame)
admin.site.register(Podcast)
admin.site.register(Beer)
admin.site.register(Wine)
admin.site.register(Cheese)
admin.site.register(PursuitProgress)
admin.site.register(Travel)


admin.site.register(FoodItem)
admin.site.register(FoodStock)
admin.site.register(Recipe)
admin.site.register(RecipeIngredients)
admin.site.register(GroceryPurchase)
admin.site.register(Cooking)
admin.site.register(Meal)