from django.conf.urls import url, include
from .drf_views import *

urlpatterns = [
	url(r'^today$', TodayDataFilled.as_view()),

	url(r'^modules$', ModuleButtonList.as_view()),
	url(r'^modules/(?P<pk>[0-9]+)$', ModuleButtonDetails.as_view()),

	url(r'^overview$', OverviewList.as_view()),
	url(r'^overview/(?P<pk>[0-9]+)$', OverviewDetails.as_view()),
	url(r'^overview/(?P<date>\d{4}-\d{2}-\d{2})$', OverviewList.as_view()),

	url(r'^sleep$', SleepList.as_view()),
	url(r'^sleep/(?P<pk>[0-9]+)$', SleepDetails.as_view()),
	url(r'^sleep/(?P<date>\d{4}-\d{2}-\d{2})$', SleepList.as_view()),
	url(r'^weight$', WeightList.as_view()),
	url(r'^weight/(?P<pk>[0-9]+)$', WeightDetails.as_view()),
	url(r'^weight/(?P<date>\d{4}-\d{2}-\d{2})$', WeightList.as_view()),
	url(r'^cardio$', CardioList.as_view()),
	url(r'^cardio/(?P<pk>[0-9]+)$', CardioDetails.as_view()),
	url(r'^cardio/(?P<date>\d{4}-\d{2}-\d{2})$', CardioList.as_view()),
	url(r'^food$', FoodList.as_view()),
	url(r'^food/(?P<pk>[0-9]+)$', FoodDetails.as_view()),
	url(r'^food/(?P<date>\d{4}-\d{2}-\d{2})$', FoodList.as_view()),
	url(r'^toilet$', ToiletList.as_view()),
	url(r'^toilet/(?P<pk>[0-9]+)$', ToiletDetails.as_view()),
	url(r'^toilet/(?P<date>\d{4}-\d{2}-\d{2})$', ToiletList.as_view()),
	url(r'^sex$', SexList.as_view()),
	url(r'^sex/(?P<pk>[0-9]+)$', SexDetails.as_view()),
	url(r'^sex/(?P<date>\d{4}-\d{2}-\d{2})$', SexList.as_view()),
	url(r'^period$', PeriodList.as_view()),
	url(r'^period/(?P<pk>[0-9]+)$', PeriodDetails.as_view()),
	url(r'^period/(?P<date>\d{4}-\d{2}-\d{2})$', PeriodList.as_view()),
	
	url(r'^weightTypes$', WeightTypeList.as_view()),
	url(r'^weightTypes/(?P<pk>[0-9]+)$', WeightTypeDetails.as_view()),
	url(r'^cardioTypes$', CardioTypeList.as_view()),
	url(r'^cardioTypes/(?P<pk>[0-9]+)$', CardioTypeDetails.as_view()),

	url(r'^learning$', LearningList.as_view()),
	url(r'^learning/(?P<pk>[0-9]+)$', LearningDetails.as_view()),
	url(r'^learning/(?P<date>\d{4}-\d{2}-\d{2})$', LearningList.as_view()),
	url(r'^study$', StudyList.as_view()),
	url(r'^study/(?P<pk>[0-9]+)$', StudyDetails.as_view()),
	url(r'^study/(?P<date>\d{4}-\d{2}-\d{2})$', StudyList.as_view()),
	url(r'^money$', MoneyList.as_view()),
	url(r'^money/(?P<pk>[0-9]+)$', MoneyDetails.as_view()),
	url(r'^money/(?P<date>\d{4}-\d{2}-\d{2})$', MoneyList.as_view()),
	url(r'^todo$', ToDoList.as_view()),
	url(r'^todo/(?P<pk>[0-9]+)$', ToDoDetails.as_view()),
	url(r'^todo/(?P<date>\d{4}-\d{2}-\d{2})$', ToDoList.as_view()),
	url(r'^pursuits$', PursuitList.as_view()),
	url(r'^pursuits/(?P<pk>[0-9]+)$', PursuitDetails.as_view()),
	url(r'^projects/(?P<pk>[0-9]+)$', ProjectDetails.as_view()),
	url(r'^projects$', ProjectList.as_view()),
	url(r'^quiz/(?P<pk>[0-9]+)$', QuizDetails.as_view()),
	url(r'^quizzes$', QuizList.as_view()),
	url(r'^pursuitprogress$', PursuitProgressList.as_view()),
	url(r'^pursuitprogress/(?P<pk>[0-9]+)$', PursuitProgressDetails.as_view()),
	url(r'^pursuitprogress/(?P<date>\d{4}-\d{2}-\d{2})$', PursuitProgressList.as_view()),

	url(r'^literature$', LiteratureList.as_view()),
	url(r'^literature/(?P<pk>[0-9]+)$', LiteratureDetails.as_view()),
	url(r'^literature/(?P<date>\d{4}-\d{2}-\d{2})$', LiteratureList.as_view()),
	url(r'^film$', FilmList.as_view()),
	url(r'^film/(?P<pk>[0-9]+)$', FilmDetails.as_view()),
	url(r'^film/(?P<date>\d{4}-\d{2}-\d{2})$', FilmList.as_view()),
	url(r'^television$', TelevisionList.as_view()),
	url(r'^television/(?P<pk>[0-9]+)$', TelevisionDetails.as_view()),
	url(r'^television/(?P<date>\d{4}-\d{2}-\d{2})$', TelevisionList.as_view()),
	url(r'^boardgame$', BoardGameList.as_view()),
	url(r'^boardgame/(?P<pk>[0-9]+)$', BoardGameDetails.as_view()),
	url(r'^boardgame/(?P<date>\d{4}-\d{2}-\d{2})$', BoardGameList.as_view()),
	url(r'^videogame$', VideoGameList.as_view()),
	url(r'^videogame/(?P<pk>[0-9]+)$', VideoGameDetails.as_view()),
	url(r'^videogame/(?P<date>\d{4}-\d{2}-\d{2})$', VideoGameList.as_view()),
	url(r'^music$', MusicList.as_view()),
	url(r'^music/(?P<pk>[0-9]+)$', MusicDetails.as_view()),
	url(r'^music/(?P<date>\d{4}-\d{2}-\d{2})$', MusicList.as_view()),
	url(r'^podcast$', PodcastList.as_view()),
	url(r'^podcast/(?P<pk>[0-9]+)$', PodcastDetails.as_view()),
	url(r'^podcast/(?P<date>\d{4}-\d{2}-\d{2})$', PodcastList.as_view()),
	url(r'^beer$', BeerList.as_view()),
	url(r'^beer/(?P<pk>[0-9]+)$', BeerDetails.as_view()),
	url(r'^beer/(?P<date>\d{4}-\d{2}-\d{2})$', BeerList.as_view()),
	url(r'^wine$', WineList.as_view()),
	url(r'^wine/(?P<pk>[0-9]+)$', WineDetails.as_view()),
	url(r'^wine/(?P<date>\d{4}-\d{2}-\d{2})$', WineList.as_view()),
	url(r'^cheese$', CheeseList.as_view()),
	url(r'^cheese/(?P<pk>[0-9]+)$', CheeseDetails.as_view()),
	url(r'^cheese/(?P<date>\d{4}-\d{2}-\d{2})$', CheeseList.as_view()),

	url(r'^cooking$', CookingList.as_view()),
	url(r'^cooking/(?P<pk>[0-9]+)$', CookingDetails.as_view()),
	url(r'^cooking/(?P<date>\d{4}-\d{2}-\d{2})$', CookingList.as_view()),
	url(r'^grocerypurchase$', GroceryPurchaseList.as_view()),
	url(r'^grocerypurchase/(?P<pk>[0-9]+)$', GroceryPurchaseDetails.as_view()),
	url(r'^grocerypurchase/(?P<date>\d{4}-\d{2}-\d{2})$', GroceryPurchaseList.as_view()),
	url(r'^meal$', MealList.as_view()),
	url(r'^meal/(?P<pk>[0-9]+)$', MealDetails.as_view()),
	url(r'^meal/(?P<date>\d{4}-\d{2}-\d{2})$', MealList.as_view()),
	url(r'^travel$', TravelList.as_view()),
	url(r'^travel/(?P<pk>[0-9]+)$', TravelDetails.as_view()),
	url(r'^travel/(?P<date>\d{4}-\d{2}-\d{2})$', TravelList.as_view()),

	url(r'^foodItems/(?P<pk>[0-9]+)$', FoodItemDetails.as_view()),
	url(r'^foodItems$', FoodItemList.as_view()),
	url(r'^recipe/(?P<pk>[0-9]+)$', RecipeDetails.as_view()),
	url(r'^recipes$', RecipeList.as_view()),
	url(r'^recipeingredients/(?P<pk>[0-9]+)$', RecipeIngredientsDetails.as_view()),
	url(r'^recipeingredients$', RecipeIngredientsList.as_view()),
	url(r'^filmwish/(?P<pk>[0-9]+)$', FilmWishDetails.as_view()),
	url(r'^filmwish$', FilmWishList.as_view()),
	url(r'^boardgamewish/(?P<pk>[0-9]+)$', BoardGameWishDetails.as_view()),
	url(r'^boardgamewish$', BoardGameWishList.as_view()),
	url(r'^literaturewish/(?P<pk>[0-9]+)$', LiteratureWishDetails.as_view()),
	url(r'^literaturewish$', LiteratureWishList.as_view()),
]