# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-31 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_webhook_secret',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulebutton',
            name='background_color',
            field=models.TextField(default='#8bacbd'),
        ),
        migrations.AlterField(
            model_name='modulebutton',
            name='icon_source',
            field=models.CharField(choices=[('UN', 'Unicode'), ('FA', 'FontAwesome')], default='FA', max_length=2),
        ),
    ]
