# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-31 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180730_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
