# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-05 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20180604_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sex',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='cardioexercise',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='cardioexercise',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='eat_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='sex',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='weightexercise',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='weightexercise',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
