# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-06 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20180605_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sex',
            name='start_time',
        ),
    ]
