# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-06 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_sex_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='waiting_on',
            field=models.TextField(blank=True, null=True),
        ),
    ]
