# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-08 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_user_seen_intro'),
    ]

    operations = [
        migrations.RenameModel('Overview', 'Diary'),
    ]
