# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-06 20:11
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20180605_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('rating', models.DecimalField(decimal_places=1, default=3, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('highlights', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='beer',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Day'),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Day'),
        ),
        migrations.AlterField(
            model_name='cardioexercise',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Day'),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Day'),
        ),
        migrations.AlterField(
            model_name='film',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Day'),
        ),
        migrations.AlterField(
            model_name='food',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Day'),
        ),
        migrations.AlterField(
            model_name='learning',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Day'),
        ),
        migrations.AlterField(
            model_name='literature',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Day'),
        ),
        migrations.AlterField(
            model_name='money',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Day'),
        ),
        migrations.AlterField(
            model_name='music',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Day'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Day'),
        ),
        migrations.AlterField(
            model_name='period',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Day'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Day'),
        ),
        migrations.AlterField(
            model_name='sex',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Day'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Day'),
        ),
        migrations.AlterField(
            model_name='study',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Day'),
        ),
        migrations.AlterField(
            model_name='television',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Day'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Day'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Day'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Day'),
        ),
        migrations.AlterField(
            model_name='weightexercise',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Day'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Day'),
        ),
    ]
