# Generated by Django 2.0.7 on 2018-08-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20180808_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='sex',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sex',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
