# Generated by Django 2.0.7 on 2018-08-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20180813_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='television',
            name='episode_num',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='television',
            name='season_num',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
