# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-11 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20180606_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('icon', models.CharField(max_length=2)),
            ],
        ),
    ]
