# Generated by Django 2.0.7 on 2018-08-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20180813_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='episode_num',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
