# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-20 18:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_podcast_episode_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='bristol',
            field=models.IntegerField(blank=True, default=4, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
