# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-11 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20180611_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
