# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-20 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20180820_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning',
            name='urls',
            field=models.TextField(blank=True, null=True),
        ),
    ]
