# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-13 13:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20180612_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='todo',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
