# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-13 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20180613_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.TextField()),
                ('total_records', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='study',
            name='total_records',
        ),
        migrations.AddField(
            model_name='study',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Quiz'),
        ),
    ]
