# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-20 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_learning_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='literature',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='literature',
            name='up_to_page',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
