# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20180613_1207'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoCategory',
            new_name='Pursuit',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='category',
            new_name='pursuit',
        ),
    ]
