# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-21 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20180820_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='literature',
            name='up_to_chapter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
