# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20180613_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pursuit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Pursuit'),
        ),
    ]
