# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_project_pursuit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url_name', models.TextField()),
                ('background_color', models.TextField()),
                ('icon_source', models.CharField(choices=[('UN', 'Unicode'), ('FA', 'FontAwesome')], default='UN', max_length=2)),
                ('icon_unicode', models.CharField(blank=True, max_length=1, null=True)),
                ('icon_font_awesome', models.TextField(blank=True, null=True)),
                ('display', models.BooleanField(default=True)),
            ],
        ),
    ]
