# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_modulebutton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulebutton',
            name='icon_unicode',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
