# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-15 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20180614_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='rank',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
