# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-15 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_todo_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulebutton',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
