# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-15 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_auto_20180615_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('H', 'High Priority'), ('M', 'Medium Priority'), ('L', 'Low Priority')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('IN', 'Incomplete'), ('WO', 'Working'), ('PA', 'Partially Complete'), ('CO', 'Complete'), ('CA', 'Canceled'), ('SR', 'Waiting')], default='IN', max_length=2),
        ),
    ]
