# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-17 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_auto_20180616_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='correct_records',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
