# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-17 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_todo_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulebutton',
            name='background_color_complete',
            field=models.TextField(blank=True, null=True),
        ),
    ]
