# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-17 22:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_modulebutton_background_color_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='PursuitProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('description', models.TextField()),
                ('pursuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Pursuit')),
            ],
        ),
    ]
