# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-22 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_auto_20180622_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='saturated_fat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='total_fat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
