# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-22 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_fooditem_trans_fat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='saturated_fat',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='total_fat',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='trans_fat',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
