# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-22 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_auto_20180622_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='serving_size',
            field=models.TextField(default='1 serving'),
            preserve_default=False,
        ),
    ]
