# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-23 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_fooditem_serving_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='serving_size_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='serving_size_unit',
            field=models.TextField(default='serving'),
            preserve_default=False,
        ),
    ]
