# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-23 18:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0039_auto_20180623_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('name', models.TextField()),
                ('location_type', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=13, max_digits=16)),
                ('longitude', models.DecimalField(decimal_places=13, max_digits=16)),
            ],
        ),
        migrations.AlterField(
            model_name='meal',
            name='foods',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.FoodItem'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='recipes',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.Recipe'),
        ),
    ]
