# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-23 22:30
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0041_filmwish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwish',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
