# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-23 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0042_auto_20180623_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmwish',
            name='tags',
        ),
    ]
