# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-28 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0043_remove_filmwish_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGameWish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('creator', models.TextField(blank=True, null=True)),
                ('fulfillment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.BoardGame')),
            ],
        ),
        migrations.CreateModel(
            name='LiteratureWish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.TextField(blank=True, null=True)),
                ('fulfillment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Literature')),
            ],
        ),
    ]
