# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0044_boardgamewish_literaturewish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='serving_size',
        ),
    ]
