# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0045_remove_fooditem_serving_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodstock',
            name='serving_count',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='grocerypurchase',
            name='serving_count',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
