# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-06 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0047_auto_20180705_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='barcode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
