# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-22 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0048_fooditem_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='item_unit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
